package com.example.prueba.gato

class GatosProvider {
    companion object{
        val listaGatos:MutableList<Gato> = arrayListOf(
            Gato("Erza",
                 "",
                 " Hembra",
                 "",
                0,
                0,
                0,
                0
            ),
            Gato(
                "Mini",
                "",
                "Hembra",
                "",
                0,
                0,
                0,
                0
            ),
            Gato(
                "Capitán",
                "",
                "Macho",
                "",
                0,
                0,
                0,
                0
            ),
            Gato(
                "Manteca",
                "",
                "Hembra",
                "",
                0,
                0,
                0,
                0
            ),
            Gato(
                "Milaneso",
                "",
                "Macho",
                "",
                0,
                0,
                0,
                0
            ),
            Gato(
                "Jupiter",
                "",
                "Macho",
                "",
                0,
                0,
                0,
                0
            ),
            Gato(
                "Fideo",
                "",
                "Macho",
                "",
                0,
                0,
                0,
                0
            ),
            Gato(
                "Palm",
                "",
                "Hembra",
                "",
                0,
                0,
                0,
                0
            ),
            Gato(
                "Pipa",
                "",
                "Macho",
                "",
                0,
                0,
                0,
                0
            ),
            Gato(
                "Taylor",
                "",
                "Hembra",
                "",
                0,
                0,
                0,
                0
            ),
            Gato(
                "Messi",
                "",
                "Macho",
                "",
                0,
                0,
                0,
                0
            ),
            Gato(
                "Lua",
                "",
                "Hembra",
                "",
                0,
                0,
                0,
                0
            ),
            Gato(
                "Mulan",
                "",
                "Hembra",
                "",
                0,
                0,
                0,
                0
            ),
            Gato(
                "Michi",
                "",
                "Macho",
                "",
                0,
                0,
                0,
                0
            ),
            Gato(
                "Choripan",
                "",
                "Macho",
                "",
                0,
                0,
                0,
                0
            ),
            Gato(
                "Katara",
                "",
                "Hembra",
                "",
                0,
                0,
                0,
                0)
        )
    }
}